<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>10-recommended</AnalysisLevel>
    </PropertyGroup>
</Project>